"""생성 상수 — shared/generated/ 에 놓는 세 벌. 검사가 세는 것만 만든다.

  ApiRoutes     api/openapi.yaml 의 라우트         (앱이 부르는 이름 = 검사가 세는 이름)
  Screens       design/ 의 화면 id
  DesignTokens  design/ 의 토큰 (색은 hex 문자열, 치수는 숫자)

같은 입력이면 같은 바이트다 — 워크트리마다 놓아도 셋이 같고, 손댔는지는 바이트 대조(drift)로 안다.
"""
import hashlib
import os
import re

from . import api, util

SWIFT_KW = {"as", "class", "default", "enum", "extension", "func", "import", "in", "init", "is",
            "let", "nil", "operator", "private", "protocol", "public", "return", "self", "static",
            "struct", "switch", "true", "false", "var", "where", "case", "for", "if", "else"}
KOTLIN_KW = {"as", "class", "do", "else", "false", "for", "fun", "if", "in", "is", "null", "object",
             "package", "return", "super", "this", "throw", "true", "try", "typealias", "val",
             "var", "when", "while", "interface", "import"}


def ident(name, upper=False):
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", str(name)) if p]
    if not parts:
        return "x"
    words = []
    for p in parts:
        words += re.findall(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|\d+", p) or [p]
    out = "".join(w[:1].upper() + w[1:].lower() for w in words)
    if not upper:
        out = out[:1].lower() + out[1:]
    if out[0].isdigit():
        out = "_" + out
    return out


def _swift_name(n):
    return f"`{n}`" if n in SWIFT_KW else n


def _kotlin_name(n):
    return f"`{n}`" if n in KOTLIN_KW else n


def _sha12(text):
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def _header(kind, source, sha, version):
    return (f"// handoff v{version} · {kind} · from {source} ({sha}) — generated by the server; "
            f"never edit, never regenerate\n")


# ─────────────────────────── ApiRoutes ───────────────────────────

def _routes_swift(rs, hdr):
    lines = [hdr, "import Foundation", "", "public enum ApiRoutes {",
             "    public struct Route { public let method: String; public let path: String }", ""]
    for r in rs:
        lines.append(f"    /// {r['method']} {r['path']}" + (f" — {r['summary']}" if r['summary'] else ""))
        lines.append(f"    public static let {_swift_name(r['name'])} = "
                     f"Route(method: \"{r['method']}\", path: \"{r['path']}\")")
    lines += ["}", ""]
    return "\n".join(lines)


def _routes_kotlin(rs, hdr, pkg):
    lines = [hdr, f"package {pkg}", "", "object ApiRoutes {",
             "    data class Route(val method: String, val path: String)", ""]
    for r in rs:
        lines.append(f"    /** {r['method']} {r['path']}" + (f" — {r['summary']}" if r['summary'] else "") + " */")
        lines.append(f"    val {_kotlin_name(r['name'])} = Route(\"{r['method']}\", \"{r['path']}\")")
    lines += ["}", ""]
    return "\n".join(lines)


# ─────────────────────────── Screens ───────────────────────────

def _screens_swift(screens, hdr):
    lines = [hdr, "public enum Screens {"]
    for s in screens:
        lines.append(f"    /// {s['title']}" + (f" — design/{s['file']}" if s.get('file') else ""))
        lines.append(f"    public static let {_swift_name(s['id'])} = \"{s['id']}\"")
    lines += ["}", ""]
    return "\n".join(lines)


def _screens_kotlin(screens, hdr, pkg):
    lines = [hdr, f"package {pkg}", "", "object Screens {"]
    for s in screens:
        lines.append(f"    /** {s['title']}" + (f" — design/{s['file']}" if s.get('file') else "") + " */")
        lines.append(f"    const val {_kotlin_name(s['id'])} = \"{s['id']}\"")
    lines += ["}", ""]
    return "\n".join(lines)


# ─────────────────────────── DesignTokens ───────────────────────────

def token_tree(tokens):
    """{'color.accent': {...}} → 중첩 dict. 잎은 토큰 dict, 가지는 dict."""
    tree = {}
    for key, tok in sorted(tokens.items()):
        parts = key.split(".")
        node = tree
        for p in parts[:-1]:
            node = node.setdefault(ident(p, upper=True), {})
            if "kind" in node:                    # 잎 위에 가지가 오면 잎을 밀어낸다
                node.clear()
        leaf = ident(parts[-1])
        if isinstance(node.get(leaf), dict) and "kind" not in node[leaf]:
            node[leaf]["value_"] = {**tok, "key": key}
        else:
            node[leaf] = {**tok, "key": key}
    return tree


def token_consts(tokens):
    """{'color.accent': 'DesignTokens.Color.accent'} — 소비 스캔·파리티·하드코딩 검출의 이름."""
    out = {}
    for key in tokens:
        parts = key.split(".")
        path = [ident(p, upper=True) for p in parts[:-1]] + [ident(parts[-1])]
        out[key] = "DesignTokens." + ".".join(path)
    return out


def _fmt(tok, lang):
    v = tok["value"]
    if tok["kind"] == "dimension":
        num = float(v)
        s = str(int(num)) if num.is_integer() else repr(num)
        return (f"CGFloat({s})" if lang == "swift" else f"{s}f"), ("CGFloat" if lang == "swift" else "Float")
    return ('"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'), "String"


def _emit_swift(node, depth):
    pad = "    " * depth
    lines = []
    for name in sorted(node):
        val = node[name]
        if "kind" in val:
            lit, typ = _fmt(val, "swift")
            lines.append(f"{pad}/// {val['key']} = {val['value']}")
            lines.append(f"{pad}public static let {_swift_name(name)}: {typ} = {lit}")
        else:
            lines.append(f"{pad}public enum {name} {{")
            lines += _emit_swift(val, depth + 1)
            lines.append(f"{pad}}}")
    return lines


def _emit_kotlin(node, depth):
    pad = "    " * depth
    lines = []
    for name in sorted(node):
        val = node[name]
        if "kind" in val:
            lit, typ = _fmt(val, "kotlin")
            lines.append(f"{pad}/** {val['key']} = {val['value']} */")
            lines.append(f"{pad}val {_kotlin_name(name)}: {typ} = {lit}")
        else:
            lines.append(f"{pad}object {name} {{")
            lines += _emit_kotlin(val, depth + 1)
            lines.append(f"{pad}}}")
    return lines


def _tokens_swift(tokens, hdr):
    return "\n".join([hdr, "import CoreGraphics", "", "public enum DesignTokens {"]
                     + _emit_swift(token_tree(tokens), 1) + ["}", ""])


def _tokens_kotlin(tokens, hdr, pkg):
    return "\n".join([hdr, f"package {pkg}", "", "object DesignTokens {"]
                     + _emit_kotlin(token_tree(tokens), 1) + ["}", ""])


# ─────────────────────────── 조립 ───────────────────────────

def expected(root, cfg, version, manifest, routes):
    """{상대경로: 내용}. 스펙의 플랫폼에 맞춰 Swift/Kotlin 을 낸다."""
    plats = set(util.platforms(root))
    pkg = cfg.get("kotlin_package", "shared.generated")
    out = {}
    api_sha = _sha12(util.read_text(util.api_path(root)))
    d_sha = (manifest.get("hash") or "")[:12]
    emits = [
        ("ApiRoutes", f"{util.API_DIR}/{util.API_FILE}", api_sha,
         lambda h: _routes_swift(routes, h), lambda h: _routes_kotlin(routes, h, pkg)),
        ("Screens", "design/", d_sha,
         lambda h: _screens_swift(manifest["screens"], h),
         lambda h: _screens_kotlin(manifest["screens"], h, pkg)),
    ]
    if manifest.get("tokens"):
        emits.append(("DesignTokens", "design/", d_sha,
                      lambda h: _tokens_swift(manifest["tokens"], h),
                      lambda h: _tokens_kotlin(manifest["tokens"], h, pkg)))
    for kind, src, sha, sw, kt in emits:
        hdr = _header(kind, src, sha, version)
        if "ios" in plats:
            out[f"{util.GEN_DIR}/{kind}.swift"] = sw(hdr)
        if "android" in plats:
            out[f"{util.GEN_DIR}/{kind}.kt"] = kt(hdr)
    return out


def write(dest, files):
    """dest 아래에 놓는다. 목록에 없는 생성물은 지운다(잉여가 남으면 대조가 어긋난다)."""
    gen_dir = os.path.join(dest, util.GEN_DIR)
    os.makedirs(gen_dir, exist_ok=True)
    for rel, content in files.items():
        util.write_text(os.path.join(dest, rel), content)
    for n in os.listdir(gen_dir):
        if f"{util.GEN_DIR}/{n}" not in files and os.path.isfile(os.path.join(gen_dir, n)):
            os.remove(os.path.join(gen_dir, n))
    return sorted(files)


def drift(dest, files):
    """바이트 대조. [(사유, 경로)] — 없음 · 다름 · 잉여."""
    out = []
    for rel, content in files.items():
        p = os.path.join(dest, rel)
        if not os.path.isfile(p):
            out.append(("missing", rel))
        elif util.read_text(p) != content:
            out.append(("modified", rel))
    gen_dir = os.path.join(dest, util.GEN_DIR)
    if os.path.isdir(gen_dir):
        for n in sorted(os.listdir(gen_dir)):
            rel = f"{util.GEN_DIR}/{n}"
            if rel not in files and os.path.isfile(os.path.join(gen_dir, n)):
                out.append(("extra", rel))
    return out
