"""생성 상수 — shared/generated/ 에 놓는 세 벌. 검사가 세는 것만 만든다.

  ApiRoutes     api/openapi.yaml 의 라우트         (앱이 부르는 이름 = 검사가 세는 이름)
  Screens       design/ 의 화면 id                 (web 은 ScreenPaths 도 같은 파일에 — URL 경로)
  DesignTokens  design/ 의 토큰 (색은 hex 문자열, 치수는 숫자)

플랫폼별 언어: ios → .swift · android → .kt · web → .ts (+ tokens.css — CSS 가 토큰을 소비하는 통로, 변수명은 토큰 키의 `-` 표기).
같은 입력이면 같은 바이트다 — 워크트리마다 놓아도 셋이 같고, 손댔는지는 바이트 대조(drift)로 안다.
"""
import hashlib
import os
import re

from . import api, util

SWIFT_KW = {"as", "class", "default", "enum", "extension", "func", "import", "in", "init", "is",
            "let", "nil", "operator", "private", "protocol", "public", "return", "self", "static",
            "struct", "switch", "true", "false", "var", "where", "case", "for", "if", "else"}
KOTLIN_KW = {"as", "class", "do", "else", "false", "for", "fun", "if", "in", "is", "null", "object",
             "package", "return", "super", "this", "throw", "true", "try", "typealias", "val",
             "var", "when", "while", "interface", "import"}


def ident(name, upper=False):
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", str(name)) if p]
    if not parts:
        return "x"
    words = []
    for p in parts:
        words += re.findall(r"[A-Z]+(?=[A-Z][a-z])|[A-Z]?[a-z]+|[A-Z]+|\d+", p) or [p]
    out = "".join(w[:1].upper() + w[1:].lower() for w in words)
    if not upper:
        out = out[:1].lower() + out[1:]
    if out[0].isdigit():
        out = "_" + out
    return out


def _swift_name(n):
    return f"`{n}`" if n in SWIFT_KW else n


def _kotlin_name(n):
    return f"`{n}`" if n in KOTLIN_KW else n


def _sha12(text):
    return hashlib.sha256(text.encode()).hexdigest()[:12]


def _ts_str(v):
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def css_var(key):
    """토큰 키 → CSS 변수 이름. 'color.accent' → '--color-accent' (프로토타입의 var(--color-accent) 와 같은 표기)."""
    return "--" + str(key).replace(".", "-")


def _header(kind, source, sha, version):
    return (f"// handoff v{version} · {kind} · from {source} ({sha}) — generated by the server; "
            f"never edit, never regenerate\n")


# ─────────────────────────── ApiRoutes ───────────────────────────

def _routes_swift(rs, hdr):
    lines = [hdr, "import Foundation", "", "public enum ApiRoutes {",
             "    public struct Route { public let method: String; public let path: String }", ""]
    for r in rs:
        lines.append(f"    /// {r['method']} {r['path']}" + (f" — {r['summary']}" if r['summary'] else ""))
        lines.append(f"    public static let {_swift_name(r['name'])} = "
                     f"Route(method: \"{r['method']}\", path: \"{r['path']}\")")
    lines += ["}", ""]
    return "\n".join(lines)


def _routes_kotlin(rs, hdr, pkg):
    lines = [hdr, f"package {pkg}", "", "object ApiRoutes {",
             "    data class Route(val method: String, val path: String)", ""]
    for r in rs:
        lines.append(f"    /** {r['method']} {r['path']}" + (f" — {r['summary']}" if r['summary'] else "") + " */")
        lines.append(f"    val {_kotlin_name(r['name'])} = Route(\"{r['method']}\", \"{r['path']}\")")
    lines += ["}", ""]
    return "\n".join(lines)


def _routes_ts(rs, hdr):
    """TS 는 예약어도 속성 이름으로 쓸 수 있어 이스케이프가 없다. 객체 리터럴 + as const."""
    lines = [hdr, "export interface Route { readonly method: string; readonly path: string }", "",
             "export const ApiRoutes = {"]
    for r in rs:
        lines.append(f"  /** {r['method']} {r['path']}" + (f" — {r['summary']}" if r['summary'] else "") + " */")
        lines.append(f"  {r['name']}: {{ method: \"{r['method']}\", path: \"{r['path']}\" }},")
    lines += ["} as const satisfies Record<string, Route>;", ""]
    return "\n".join(lines)


# ─────────────────────────── Screens ───────────────────────────

def _screens_ts(screens, hdr):
    lines = [hdr, "export const Screens = {"]
    for s in screens:
        lines.append(f"  /** {s['title']}" + (f" — design/{s['file']}" if s.get('file') else "") + " */")
        lines.append(f"  {s['id']}: \"{s['id']}\",")
    lines += ["} as const;", "", "export type ScreenId = (typeof Screens)[keyof typeof Screens];", "",
              "/** URL path per screen — the human-confirmed route (design/handoff.manifest.json → screens[].path). */",
              "export const ScreenPaths: Record<ScreenId, string> = {"]
    for s in screens:
        lines.append(f"  {s['id']}: \"{s.get('path') or '/' + s['id']}\",")
    lines += ["};", ""]
    return "\n".join(lines)


def _screens_swift(screens, hdr):
    lines = [hdr, "public enum Screens {"]
    for s in screens:
        lines.append(f"    /// {s['title']}" + (f" — design/{s['file']}" if s.get('file') else ""))
        lines.append(f"    public static let {_swift_name(s['id'])} = \"{s['id']}\"")
    lines += ["}", ""]
    return "\n".join(lines)


def _screens_kotlin(screens, hdr, pkg):
    lines = [hdr, f"package {pkg}", "", "object Screens {"]
    for s in screens:
        lines.append(f"    /** {s['title']}" + (f" — design/{s['file']}" if s.get('file') else "") + " */")
        lines.append(f"    const val {_kotlin_name(s['id'])} = \"{s['id']}\"")
    lines += ["}", ""]
    return "\n".join(lines)


# ─────────────────────────── DesignTokens ───────────────────────────

def token_tree(tokens):
    """{'color.accent': {...}} → 중첩 dict. 잎은 토큰 dict, 가지는 dict."""
    tree = {}
    for key, tok in sorted(tokens.items()):
        parts = key.split(".")
        node = tree
        for p in parts[:-1]:
            node = node.setdefault(ident(p, upper=True), {})
            if "kind" in node:                    # 잎 위에 가지가 오면 잎을 밀어낸다
                node.clear()
        leaf = ident(parts[-1])
        if isinstance(node.get(leaf), dict) and "kind" not in node[leaf]:
            node[leaf]["value_"] = {**tok, "key": key}
        else:
            node[leaf] = {**tok, "key": key}
    return tree


def token_consts(tokens):
    """{'color.accent': 'DesignTokens.Color.accent'} — 소비 스캔·파리티·하드코딩 검출의 이름."""
    out = {}
    for key in tokens:
        parts = key.split(".")
        path = [ident(p, upper=True) for p in parts[:-1]] + [ident(parts[-1])]
        out[key] = "DesignTokens." + ".".join(path)
    return out


def _fmt(tok, lang):
    v = tok["value"]
    if tok["kind"] == "dimension":
        num = float(v)
        s = str(int(num)) if num.is_integer() else repr(num)
        return (f"CGFloat({s})" if lang == "swift" else f"{s}f"), ("CGFloat" if lang == "swift" else "Float")
    return ('"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'), "String"


def _emit_swift(node, depth):
    pad = "    " * depth
    lines = []
    for name in sorted(node):
        val = node[name]
        if "kind" in val:
            lit, typ = _fmt(val, "swift")
            lines.append(f"{pad}/// {val['key']} = {val['value']}")
            lines.append(f"{pad}public static let {_swift_name(name)}: {typ} = {lit}")
        else:
            lines.append(f"{pad}public enum {name} {{")
            lines += _emit_swift(val, depth + 1)
            lines.append(f"{pad}}}")
    return lines


def _emit_kotlin(node, depth):
    pad = "    " * depth
    lines = []
    for name in sorted(node):
        val = node[name]
        if "kind" in val:
            lit, typ = _fmt(val, "kotlin")
            lines.append(f"{pad}/** {val['key']} = {val['value']} */")
            lines.append(f"{pad}val {_kotlin_name(name)}: {typ} = {lit}")
        else:
            lines.append(f"{pad}object {name} {{")
            lines += _emit_kotlin(val, depth + 1)
            lines.append(f"{pad}}}")
    return lines


def _emit_ts(node, depth):
    pad = "  " * depth
    lines = []
    for name in sorted(node):
        val = node[name]
        if "kind" in val:
            if val["kind"] == "dimension":
                num = float(val["value"])
                lit = str(int(num)) if num.is_integer() else repr(num)
            else:
                lit = _ts_str(val["value"])
            lines.append(f"{pad}/** {val['key']} = {val['value']} — CSS: var({css_var(val['key'])}) */")
            lines.append(f"{pad}{name}: {lit},")
        else:
            lines.append(f"{pad}{name}: {{")
            lines += _emit_ts(val, depth + 1)
            lines.append(f"{pad}}},")
    return lines


def _tokens_ts(tokens, hdr):
    return "\n".join([hdr, "/** Dimensions are px numbers; colors are strings. In CSS use the same tokens as var(--key-with-dashes) from tokens.css. */",
                      "export const DesignTokens = {"] + _emit_ts(token_tree(tokens), 1) + ["} as const;", ""])


def _tokens_css(tokens, hdr):
    """:root 커스텀 프로퍼티 한 벌 — 변수명은 토큰 키의 `-` 표기라 프로토타입 CSS 의 var(--x) 가 그대로 맞는다."""
    L = ["/*" + hdr.strip().lstrip("/").strip() + " */", ":root {"]
    for key, tok in sorted(tokens.items()):
        v = tok["value"]
        if tok["kind"] == "dimension":
            num = float(v)
            v = (str(int(num)) if num.is_integer() else repr(num)) + "px"
        L.append(f"  {css_var(key)}: {v};")
    L += ["}", ""]
    return "\n".join(L)


def _tokens_swift(tokens, hdr):
    return "\n".join([hdr, "import CoreGraphics", "", "public enum DesignTokens {"]
                     + _emit_swift(token_tree(tokens), 1) + ["}", ""])


def _tokens_kotlin(tokens, hdr, pkg):
    return "\n".join([hdr, f"package {pkg}", "", "object DesignTokens {"]
                     + _emit_kotlin(token_tree(tokens), 1) + ["}", ""])


# ─────────────────────────── Strings · Icons (derived/) ───────────────────────────

def _string_tree(rows):
    """[{key:'home.title', text}] → {Home: {title: text}} (첫 조각이 그룹)"""
    tree = {}
    for r in rows:
        grp, _, leaf = r["key"].partition(".")
        leaf = ident(leaf.replace(".", " "))
        tree.setdefault(ident(grp, upper=True), {})[leaf] = r["text"]
    return tree


def _strings_swift(rows, hdr):
    L = [hdr, "public enum Strings {"]
    for grp, items in sorted(_string_tree(rows).items()):
        L.append(f"    public enum {grp} {{")
        for k, v in sorted(items.items()):
            L.append(f"        public static let {_swift_name(k)} = \"{v.replace(chr(92), chr(92)*2).replace(chr(34), chr(92)+chr(34))}\"")
        L.append("    }")
    L += ["}", ""]
    return "\n".join(L)


def _strings_kotlin(rows, hdr, pkg):
    L = [hdr, f"package {pkg}", "", "object Strings {"]
    for grp, items in sorted(_string_tree(rows).items()):
        L.append(f"    object {grp} {{")
        for k, v in sorted(items.items()):
            L.append(f"        const val {_kotlin_name(k)} = \"{v.replace(chr(92), chr(92)*2).replace(chr(34), chr(92)+chr(34)).replace('$', '${chr(36)}')}\"")
        L.append("    }")
    L += ["}", ""]
    return "\n".join(L)


def _strings_ts(rows, hdr):
    L = [hdr, "export const Strings = {"]
    for grp, items in sorted(_string_tree(rows).items()):
        L.append(f"  {grp}: {{")
        for k, v in sorted(items.items()):
            L.append(f"    {k}: {_ts_str(v)},")
        L.append("  },")
    L += ["} as const;", ""]
    return "\n".join(L)


def _icons_ts(icons, hdr):
    L = [hdr, "/** Icon names — each is design/derived/icons/<name>.svg. Import the SVG through a bundler alias; never copy the file. */",
         "export const Icons = {"]
    for i in icons:
        L.append(f"  {ident(i['name'])}: \"{i['name']}\",")
    L += ["} as const;", ""]
    return "\n".join(L)


def _icons_swift(icons, hdr):
    L = [hdr, "/// Asset names — add each design/derived/icons/<name>.svg to the asset catalog under the same name.",
         "public enum Icons {"]
    for i in icons:
        L.append(f"    public static let {_swift_name(ident(i['name']))} = \"{i['name']}\"")
    L += ["}", ""]
    return "\n".join(L)


def _icons_kotlin(icons, hdr, pkg):
    L = [hdr, f"package {pkg}", "", "/** Drawable names — import each design/derived/icons/<name>.svg as a vector drawable ic_<snake_name>. */",
         "object Icons {"]
    for i in icons:
        L.append(f"    const val {_kotlin_name(ident(i['name']))} = \"{i['name']}\"")
    L += ["}", ""]
    return "\n".join(L)


# ─────────────────────────── 조립 ───────────────────────────

def expected(root, cfg, version, manifest, routes):
    """{상대경로: 내용}. 스펙의 플랫폼에 맞춰 Swift/Kotlin 을 낸다."""
    plats = set(util.platforms(root))
    pkg = cfg.get("kotlin_package", "shared.generated")
    out = {}
    api_sha = _sha12(util.read_text(util.api_path(root)))
    d_sha = (manifest.get("hash") or "")[:12]
    emits = [
        ("ApiRoutes", f"{util.API_DIR}/{util.API_FILE}", api_sha,
         lambda h: _routes_swift(routes, h), lambda h: _routes_kotlin(routes, h, pkg), lambda h: _routes_ts(routes, h)),
        ("Screens", "design/", d_sha,
         lambda h: _screens_swift(manifest["screens"], h),
         lambda h: _screens_kotlin(manifest["screens"], h, pkg),
         lambda h: _screens_ts(manifest["screens"], h)),
    ]
    if manifest.get("tokens"):
        emits.append(("DesignTokens", "design/", d_sha,
                      lambda h: _tokens_swift(manifest["tokens"], h),
                      lambda h: _tokens_kotlin(manifest["tokens"], h, pkg),
                      lambda h: _tokens_ts(manifest["tokens"], h)))
    from . import derive
    strs = (derive.read(root, "strings.json") or {}).get("strings") or []
    if strs:
        emits.append(("Strings", "design/derived/strings.json", d_sha,
                      lambda h: _strings_swift(strs, h), lambda h: _strings_kotlin(strs, h, pkg), lambda h: _strings_ts(strs, h)))
    ics = (derive.read(root, "icons.json") or {}).get("icons") or []
    if ics:
        emits.append(("Icons", "design/derived/icons.json", d_sha,
                      lambda h: _icons_swift(ics, h), lambda h: _icons_kotlin(ics, h, pkg), lambda h: _icons_ts(ics, h)))
    for kind, src, sha, sw, kt, ts in emits:
        hdr = _header(kind, src, sha, version)
        if "ios" in plats:
            out[f"{util.GEN_DIR}/{kind}.swift"] = sw(hdr)
        if "android" in plats:
            out[f"{util.GEN_DIR}/{kind}.kt"] = kt(hdr)
        if "web" in plats:
            out[f"{util.GEN_DIR}/{kind}.ts"] = ts(hdr)
    if "web" in plats and manifest.get("tokens"):
        out[f"{util.GEN_DIR}/tokens.css"] = _tokens_css(manifest["tokens"], _header("DesignTokens (CSS)", "design/", d_sha, version))
    return out


def write(dest, files):
    """dest 아래에 놓는다. 목록에 없는 생성물은 지운다(잉여가 남으면 대조가 어긋난다)."""
    gen_dir = os.path.join(dest, util.GEN_DIR)
    os.makedirs(gen_dir, exist_ok=True)
    for rel, content in files.items():
        util.write_text(os.path.join(dest, rel), content)
    for n in os.listdir(gen_dir):
        if f"{util.GEN_DIR}/{n}" not in files and os.path.isfile(os.path.join(gen_dir, n)):
            os.remove(os.path.join(gen_dir, n))
    return sorted(files)


def drift(dest, files):
    """바이트 대조. [(사유, 경로)] — 없음 · 다름 · 잉여."""
    out = []
    for rel, content in files.items():
        p = os.path.join(dest, rel)
        if not os.path.isfile(p):
            out.append(("missing", rel))
        elif util.read_text(p) != content:
            out.append(("modified", rel))
    gen_dir = os.path.join(dest, util.GEN_DIR)
    if os.path.isdir(gen_dir):
        for n in sorted(os.listdir(gen_dir)):
            rel = f"{util.GEN_DIR}/{n}"
            if rel not in files and os.path.isfile(os.path.join(gen_dir, n)):
                out.append(("extra", rel))
    return out
